name: Despliegue a EC2

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Construir WAR
        run: mvn clean install -DskipTests

      - name: Empaquetar WAR y script Python
        run: |
          mkdir deploy
          cp target/ROOT.war deploy/
          cp prediccion_stock.py deploy/
          tar -czf deploy.tar.gz -C deploy .

      - name: Subir archivos a EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 3.230.201.137
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: deploy.tar.gz
          target: /home/ubuntu/

      - name: Extraer, mover y configurar en EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 3.230.201.137
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu
            tar -xzf deploy.tar.gz

            # Mover WAR al Tomcat
            sudo mv ROOT.war /var/lib/tomcat10/webapps/

            # Verificar entorno virtual
            if [ ! -d "/home/ubuntu/optistock-ia-env" ]; then
              python3 -m venv /home/ubuntu/optistock-ia-env
              /home/ubuntu/optistock-ia-env/bin/pip install --upgrade pip
              /home/ubuntu/optistock-ia-env/bin/pip install pandas requests scikit-learn
            fi

            # Mover script y dar permisos
            mv prediccion_stock.py /home/ubuntu/optistock-ia-env/
            chmod +x /home/ubuntu/optistock-ia-env/prediccion_stock.py

            # Reiniciar Tomcat
            sudo systemctl restart tomcat10
